# Generated by Django 2.2.6 on 2019-11-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.AddField(
            model_name='exportreport',
            name='scheduleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.ScheduleType'),
        ),
    ]
