# Generated by Django 2.2.6 on 2019-11-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20191128_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='scheduleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.ScheduleType'),
        ),
    ]
