# Generated by Django 2.2.6 on 2019-11-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_auto_20191128_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportreport',
            name='scheduleType',
        ),
    ]
